MyDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('user/', include('user.urls')),
]

user/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # 用户登录
    path('login.html', views.loginView, name='login'),
    # 用户注册
    path('register.html', views.registerView, name='register'),
    # 修改密码
    path('setpassword.html', views.setpasswordView, name='setpassword'),
    # 注销登录
    path('logout.html', views.logoutView, name='logout'),
    # 找回密码
    path('findpassword.html', views.findPassword, name='findPassword')
]

index/models.py
from django.db import models
from django.utils.html import format_html
# Create your models here.


class Type(models.Model):
    id = models.AutoField('序号', primary_key=True)
    type_name = models.CharField('类型', max_length=20)

    def __str__(self):
        return self.type_name

    class Meta:
        verbose_name = '产品类型'
        verbose_name_plural = '产品类型'


class Product(models.Model):
    id = models.AutoField('序号', primary_key=True)
    name = models.CharField('名称', max_length=50)
    weight = models.CharField('重量', max_length=20)
    size = models.CharField('尺寸', max_length=20)
    type = models.ForeignKey(Type, on_delete=models.CASCADE, verbose_name='产品类型', )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '产品信息'
        verbose_name_plural = '产品信息'
        # 自定义用户权限
        permissions = (
            ('visit_Product', 'Can visit 产品信息'),
        )

    # 自定义字体颜色
    def colored_type(self):
        if '手机' in self.type.type_name:
            color_code = 'red'
        elif '平板电脑' in self.type.type_name:
            color_code = 'blue'
        elif '智能穿戴' in self.type.type_name:
            color_code = 'green'
        else:
            color_code = 'pink'
        return format_html('<span style="color: {};">{}</span>', color_code, self.type,)
    # 设置admin的标题
    colored_type.short_description = '带颜色的产品类型'

index/templates/ShoppingCar.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>我的购物车</title>
{% load staticfiles %}
<link rel="stylesheet" href="{% static  'css/reset.css' %}">
<link rel="stylesheet" href="{% static  'css/carts.css' %}">
</head>
<body>
<section class="cartMain">
	<div class="cartMain_hd">
		<ul class="order_lists cartTop">
			<li class="list_chk">
				<!--所有商品全选-->
				<input type="checkbox" id="all" class="whole_check">
				<label for="all"></label>
				全选
			</li>
			<li class="list_con">商品信息</li>
			<li class="list_price">单价</li>
			<li class="list_amount">数量</li>
			<li class="list_sum">金额</li>
			<li class="list_op">操作</li>
            <li class="list_op"><a href="{% url 'index' %}">返回首页</a></li>
		</ul>
	</div>
	<div class="cartBox">
		<div class="shop_info">
			<div class="all_check">
				<!--店铺全选-->
				<input type="checkbox" id="shop_b" class="shopChoice">
				<label for="shop_b" class="shop"></label>
			</div>
			<div class="shop_name">
				店铺：<a href="javascript:;">MyDjango</a>
			</div>
		</div>
		<div class="order_content">
            {% for info in product_list %}
			<ul class="order_lists">
				<li class="list_chk">
					<input type="checkbox" id="checkbox_4" class="son_check">
					<label for="checkbox_4"></label>
				</li>
				<li class="list_con">
					<div class="list_text"><a href="javascript:;">{{ info.product }}</a></div>
				</li>
				<li class="list_price">
					<p class="price">¥{{ info.price }}</p>
				</li>
				<li class="list_amount">
					<div class="amount_box">
						<a href="javascript:;" class="reduce reSty">-</a>
						<input type="text" value="1" class="sum">
						<a href="javascript:;" class="plus">+</a>
					</div>
				</li>
				<li class="list_sum">
					<p class="sum_price">¥{{ info.price }}</p>
				</li>
				<li class="list_op">
					<p class="del">
                    <a href="{% url 'ShoppingCar' %}?product={{ info.product }}" class="delBtn">移除商品</a>
                    </p>
				</li>
			</ul>
			{% endfor %}
		</div>
	</div>
	<!--底部-->
	<div class="bar-wrapper">
		<div class="bar-right">
			<div class="piece">已选商品<strong class="piece_num">0</strong>件</div>
			<div class="totalMoney">共计: <strong class="total_text">0.00</strong></div>
			<div class="calBtn"><a href="javascript:;">结算</a></div>
		</div>
	</div>
</section>
<script src="{% static  'js/jquery.min.js' %}"></script>
<script src="{% static  'js/carts.js' %}"></script>
</body>
</html>

index/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    {% block body %}
        <span>这是一个老模板</span>
    {% endblock %}
</body>
</html>

index/templates/data_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>表单</title>
</head>
<body>
    {% if product.errors %}
        <p>
            数据出错，错误信息:{{ product.errors }}
        </p>
    {% else %}
    <form action="" method="post">
        {% csrf_token %}
            <table>
                {{ product.as_table }}
            </table>
        <input type="submit" value="提交">
    </form>
    {% endif %}
</body>
</html>

index/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
    <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/hw_index.css" %}" >
    <link rel="icon" href="{% static "img/hw.ico" %}">
    <script src="{% static "js/hw_index.js" %}"></script>
</head>
<body>
<!-- 页面顶部 -->
<!-- 顶部容器 ：width:100% -->
<header id="top">
    <!-- 内容显示区域 ：width : 1211px -->
    <div id="top_box">
        <ul class="lf">
            <li><a href="#">华为官网</a></li>
            <li><a href="#">华为荣耀</a></li>
        </ul>
        <ul class="rt">
            {#在模版中使用user变量是一个User或者AnoymousUser对象，该对象由模型MyUser实例化#}
            {% if user.is_authenticated %}
                <li>用户名: {{ user.username }}</li>
                <li><a href="{% url 'logout' %}">退出登录</a></li>
            {% endif %}
            {#在模版中使用perms变量是Permission对象，该对象由模型Permission实例化#}
            {% if perms.index.add_product %}
                <li>添加产品信息</li>
            {% endif %}
        </ul>
    </div>
</header>
<!-- logo 和 搜索框 -->
<div id="top_main">
    <div class="lf  top_main_left">
        <img src="{% static "img/newLogo.png" %}" alt="" />
    </div>
    <div class="lf search_box">
        <div class="search">
            <input type="text" class="text" id="txtSearch"/>
            <input type="button" class="button" value="搜索"/>
        </div>
        <div class="hot_words">
            <span>热门搜索：</span>
            <a href="#"> 5C</a>
            <a href="#"> HUAWEI P9</a>
            <a href="#"> 5X</a>
            <a href="#">荣耀7</a>
            <a href="#"> Mate 8</a>
        </div>
    </div>
    <div class="lf" id="my_hw">我的商城</div>
    <div class="lf" id="settle_up"><a href="{% url 'ShoppingCar' %}">我的购物车</a></div>
</div><!--top_main-->

<!-- 导航 -->
<nav id="nav">
    <div id="category">
        <a href="#">全部商品</a>
    </div>
    <ul id="nav_items" class="lf">
        <li><a href="#">首页</a></li>
        <li><a href="#">华为专区</a></li>
        <li><a href="#">荣耀专区</a></li>
    </ul>
</nav>
<!-- banner 广告 -->
<div id="banner">
    <ul id="cate_box" class="lf">
        {% for type in type_list %}
        <li>
            <h3><a href="#">{{ type.type }}</a></h3>
            <p>
                {% for name in name_list %}
                    {% if name.type == type.type %}
                        <span>{{ name.name }}</span>
                    {% endif %}
                {% endfor %}
            </p>
        </li>
        {% endfor %}
    </ul>
    <!--图片轮播 -->
    <form>
        <div class="slider">
            <img id="slider_img" class="img_slider" src="{% static "img/slide01.png" %}" alt=""/>
        </div>
    </form>
</div>
<div class="hr-2"></div>
<!-- 网页主体 -->
<section id="main">
    <div class="layout">
        <div class="fl u-4-3 lf">
            <ul>
                <li class="channel-pro-item">
                    <!--<i class="p-tag"><img src="img/new_ping.png" style="padding-left: 0" alt=""/></i>-->
                    <div class="p-img">
                        <img src="{% static "img/phone01.png" %}" alt=""/>
                    </div>
                    <div class="p-name lf"><a href="#">HUAWEI P9 Plus</a></div>
                    <div class="p-shining">
                        <div class="p-slogan">一上手，就爱不释手</div>
                        <div class="p-promotions">5月6日10:08 火爆开售</div>
                    </div>
                    <div class="p-price">
                        <em>¥</em>
                        <span>3988</span>
                    </div>
                    <div class="p-button lf">
                        <a href="{% url 'index' %}?product=HUAWEI P9 Plus&price=3988">立即抢购</a>
                    </div>
                </li>
                <li class="channel-pro-item" style="background-color:#E2F9FB"><!--荣耀畅玩5C-->
                    <!--<i class="p-tag"><img src="img/new_ping02.png" alt=""/></i>-->
                    <div class="p-img">
                        <img src="{% static "img/phone02.png" %}" alt=""/>
                    </div>
                    <div class="p-name lf"><a href="#">荣耀畅玩5C</a></div>
                    <div class="p-shining">
                        <div class="p-slogan">16纳米8核芯千元普及风暴</div>
                        <div class="p-promotions">5月10日10:08震撼开售</div>
                    </div>
                    <div class="p-price">
                        <em>¥</em>
                        <span>899</span>
                    </div>
                    <div class="p-button lf">
                        <a href="{% url 'index' %}?product=荣耀畅玩5C&price=899">立即抢购</a>
                   </div>
                </li>
                <div class="hr-2"></div>
                <li class="channel-pro-item" style="background-color:#FFFCE7"><!--荣耀畅玩5C-->
                    <!--<i class="p-tag"><img src="img/hot_but.png" alt=""/></i>-->
                    <div class="p-img">
                        <img src="{% static "img/phone05.png" %}" alt=""/>
                    </div>
                    <div class="p-name lf"><a href="#">荣耀7</a></div>
                    <div class="p-shining">
                        <div class="p-slogan">智灵键，创新语音控制</div>
                        <div class="p-promotions">移动增强版原价1999直降200</div>
                    </div>
                    <div class="p-price">
                        <em>¥</em>
                        <span>1799</span>
                    </div>
                    <div class="p-button lf">
                        <a href="{% url 'index' %}?product=荣耀7&price=1799">立即抢购</a>
                    </div>
                </li>
                <li class="channel-pro-item" style="background-color:#FFECEF"><!--荣耀畅玩5C-->
                    <!--<i class="p-tag"><img src="img/hot_but.png" alt=""/></i>-->
                    <div class="p-img">
                        <img src="{% static "img/phone06.png" %}" alt=""/>
                    </div>
                    <div class="p-name lf"><a href="#">荣耀畅玩5X</a></div>
                    <div class="p-shining">
                        <div class="p-slogan">腾讯视频VIP特权免费领</div>
                        <div class="p-promotions">5月4日至8日 每天10:08/20:00准点开售</div>
                    </div>
                    <div class="p-price">
                        <em>¥</em>
                        <span>899</span>
                    </div>
                    <div class="p-button lf">
                        <a href="{% url 'index' %}?product=荣耀畅玩5X&price=899">立即抢购</a>
                    </div>
                </li>
            </ul>
        </div><!-- u-4-3结束-->
        <div class="lf fr u-4-1">
            <div class="channel-sale">
                <img src="{% static "img/phone03.jpg" %}" alt=""/>
            </div>
            <div class="hr-2"></div>
            <ul class="h-tab">
                <li class="current" id="tab-notice">
                    <a href="#">公告</a>
                </li>
                <li id="tab-news" class="">
                    <a href="#">评测 </a>
                </li>
                <div class="b">
                    <ul id="tab-notice-content" style="display:block;">
                        <li>
                            <a href="#">HUAWEI G9 青春版震撼首发，全款预订赢好礼</a>
                        </li>
                        <li>
                            <a href="#">荣耀畅玩5C，真芯不怕！ 5月5日10:08震撼首发！</a>
                        </li>
                        <li>
                            <a href="#">参与互动赢荣耀畅玩5C，与“胖红”一起怒FUN！</a>
                        </li>
                        <li>
                            <a href="#">【中奖名单】HUAWEI WATCH星月系列购机抽奖</a>
                        </li>
                    </ul>
                </div>
            </ul>
        </div>
        <div class="hr-2"></div>
        <div class="banner">
            <img class="rt" src="{% static "img/vip.jpg" %}" alt=""/>
            <div class="hr-2"></div>
        </div>
    </div><!--layout HUAWEI P9 Plus结束-->
</section>


<div class="hr-2"></div>
   <div id="banner_img">
    <div class="banner-slideshow">
        <img src="{% static "img/p9.jpg" %}" width="100%" alt=""/>
    </div>
    </div>
</div>
<div class="hr-2"></div>
<div class="hr-40"></div>
<div class="slogan">
   <ul>
       <li class="s1"><i>500强企业 品质保证</i></li>
       <li class="s1"><i>7天退货 15天换货 </i></li>
       <li class="s1"><i>99元起免运费</i></li>
       <li class="s1"><i>448家维修网点 全国联保</i></li>
   </ul>
</div>

</body>
</html>

index/templates/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>信息提示</title>
</head>
<body>
    {% if messages %}
    <ul>
        {% for message in messages %}
            {#message.tags代表信息类型#}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% else %}
        <script>alert('暂无信息')</script>
    {% endif %}
    <a href="{% url 'index' %}">返回首页</a>
    <p1>23</p1>
</body>
</html>

index/templates/myyear.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div><a href="/2018.html">{{ year }} old Archive</a></div>
    <div><a href="{% url 'myyear' 2018 %}">2018 Archive</a></div>
    <p1>{{ month }}</p1>
</body>
</html>

index/templates/pagination.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>分页功能</title>
    {# 导入CSS样式文件 #}
    {% load staticfiles %}
    <link type="text/css" rel="stylesheet" href="{% static "css/common.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static "css/pagination.css" %}">
</head>
<body>
<div class="wrapper clearfix" id="wrapper">
<div class="mod_songlist">
    <ul class="songlist__header">
        <li class="songlist__header_name">产品名称</li>
        <li class="songlist__header_author">重量</li>
        <li class="songlist__header_album">尺寸</li>
        <li class="songlist__header_other">产品类型</li>
    </ul>
    <ul class="songlist__list">
        {# 列出当前分页所对应的数据内容 #}
        {% for item in pageInfo %}
        <li class="js_songlist__child" mid="1425301" ix="6">
            <div class="songlist__item">
                <div class="songlist__songname">{{item.name}}</div>
                <div class="songlist__artist">{{item.weight}}</div>
                <div class="songlist__album">{{item.size}}</div>
                <div class="songlist__other">{{ item.type }}</div>
            </div>
        </li>
        {% endfor %}
    </ul>
    {# 分页导航 #}
    <div class="page-box">
    <div class="pagebar" id="pageBar">
    {# 上一页的URL地址 #}
    {% if pageInfo.has_previous %}
        <a href="{% url 'pagination' pageInfo.previous_page_number %}" class="prev"><i></i>上一页</a>
    {% endif %}
    {# 列出所有的URL地址 #}
    {% for num in pageInfo.paginator.page_range %}
        {% if num == pageInfo.number %}
            <span class="sel">{{ pageInfo.number }}</span>
        {% else %}
            <a href="{% url 'pagination' num %}" target="view_frame">{{num}}</a>
        {% endif %}
    {% endfor %}
    {# 下一页的URL地址 #}
    {% if pageInfo.has_next %}
        <a href="{% url 'pagination' pageInfo.next_page_number %}" class="next">下一页<i></i></a>
    {% endif %}
    </div>
    </div>
</div><!--end mod_songlist-->
</div><!--end wrapper-->
</body>
</html>

index/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{#<body>#}
{#    {% for type in type_list %}#}
{#        <div>{{ type.type }}</div>#}
{#    {% endfor %}#}
    {% for name in name %}
        {% if name.name == '手环' %}
            <div>{{ name.name }}</div>
            <div>{{ forloop.counter }}</div>
        {% endif %}
    {% endfor %}
{#    {% for id in id %}#}
{#        <div>{{ id.id }}</div>#}
{#    {% endfor %}#}
</body>
</html>